Subject: [{{HOSTNAME}}] {{SUBJECT}}
Date: {{TIMESTAMP}}

ALERT NOTIFICATION
==================

Host: {{HOSTNAME}}
Time: {{TIMESTAMP}}

Summary
-------
{{EVENT_SUMMARY}}

Source IP: {{SRC_IP}}
Failures:  {{FAIL_COUNT}}

Action Taken
------------
{{ACTION}}

--
This alert was generated by the alerting system on {{HOSTNAME}}.
Do not reply to this message.
