*{{SUBJECT}}*

*Host:* `{{HOSTNAME}}`
*Time:* `{{TIMESTAMP}}`

{{EVENT_SUMMARY}}

*Source IP:* `{{SRC_IP}}`
*Failures:* `{{FAIL_COUNT}}`
*Action:* {{ACTION}}

_Generated by alerting system on {{HOSTNAME}}_
